// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: tests.sql

package db

import (
	"context"
)

const cleanup = `-- name: Cleanup :exec
TRUNCATE transactions
`

func (q *Queries) Cleanup(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanup)
	return err
}
