// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: transactions.sql

package db

import (
	"time"
)

type CreateTransactionsParams struct {
	TransactionID      int32     `json:"transaction_id"`
	RequestID          int32     `json:"request_id"`
	TerminalID         int32     `json:"terminal_id"`
	PartnerObjectID    int32     `json:"partner_object_id"`
	AmountTotal        int32     `json:"amount_total"`
	AmountOriginal     int32     `json:"amount_original"`
	CommissionPs       int32     `json:"commission_ps"`
	CommissionClient   int32     `json:"commission_client"`
	CommissionProvider int32     `json:"commission_provider"`
	DateInput          time.Time `json:"date_input"`
	DatePost           time.Time `json:"date_post"`
	Status             string    `json:"status"`
	PaymentType        string    `json:"payment_type"`
	PaymentNumber      string    `json:"payment_number"`
	ServiceID          int32     `json:"service_id"`
	Service            string    `json:"service"`
	PayeeID            int32     `json:"payee_id"`
	PayeeName          string    `json:"payee_name"`
	PayeeBankMfo       int32     `json:"payee_bank_mfo"`
	PayeeBankAccount   string    `json:"payee_bank_account"`
	PaymentNarrative   string    `json:"payment_narrative"`
}
